name:                hmatrix-vector-sized
version:             0.1.0.0
github:              "mstksg/hmatrix-vector-sized"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Conversions between hmatrix and vector-sized types
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
    Conversions between statically sized types in hmatrix and vector-sized.

    See README on Github <https://github.com/mstksg/hmatrix-vector-sized#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- hmatrix
- vector-sized
- vector

library:
  source-dirs: src
  exposed-modules:
  - Numeric.LinearAlgebra.Static.Vector

tests:
  hmatrix-vector-sized-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmatrix-vector-sized
    - hedgehog
